name: CD

on:
  push:
    branches: [ main ]   # deploy only from main

jobs:
  deploy:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: banking
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      # ------------------------
      # Checkout repo
      # ------------------------
      - name: Checkout repository
        uses: actions/checkout@v4

      # ------------------------
      # Python setup
      # ------------------------
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # ------------------------
      # Install dbt
      # ------------------------
      - name: Install dbt postgres adapter
        run: |
          python -m pip install --upgrade pip
          pip install dbt-postgres

      # ------------------------
      # Configure dbt profile
      # ------------------------
      - name: Setup dbt profile
        run: |
          mkdir -p ~/.dbt
          cat > ~/.dbt/profiles.yml <<EOL
          banking_dbt:
            target: dev
            outputs:
              dev:
                dbname: banking
                host: localhost
                pass: ${{ secrets.POSTGRES_USER }}
                port: 5432
                schema: analytics
                threads: 1
                type: postgres
                user: ${{ secrets.POSTGRES_USER }}
          EOL

      # ------------------------
      # Deploy dbt project
      # ------------------------
      - name: dbt run + test (prod)
        run: |
          cd banking_dbt
          dbt deps
      #    dbt run    # builds production models on datawarehouse
      #    dbt test   # validates production data